apiVersion: apps/v1
kind: Deployment
metadata:
  name: oceance-kiki-lea-nginx-confmap
  labels:
    app: oceance-kiki-lea
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oceance-kiki-lea #Nom pour pointer avec le loadbalancer, SVC 
  template:
    metadata:
      labels:
        app: oceance-kiki-lea #Nom pour pointer avec le loadbalancer, SVC 
    spec:
      volumes:
        - name: configmap-html
          configMap:
            name: configmap-html
      containers:
      - name: nginx
        image: acrlp22.azurecr.io/lbnginx/erwan/webprenom-image
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: configmap-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      imagePullSecrets:
        - name: acr-secret
