name: K8S_Helm_deployment

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Package
  displayName: "Package"

  jobs:
  - job: Package
    displayName: "Package"
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: chart'
      inputs:
        PathtoPublish: chart
        ArtifactName: chart

- stage: DEV
  dependsOn: Package
  displayName: "DEV"
  jobs:
  - deployment:
    environment: dev 
    strategy:                 
      runOnce:              
        deploy:    
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: chart
              downloadPath: '$(Pipeline.Workspace)'
          - task: HelmDeploy@0
            displayName: 'helm upgrade'
            inputs:
              azureSubscription: 'AZURE_PROMEO'
              azureResourceGroup: '2023_promeo'
              kubernetesCluster: lp2023
              namespace: noah-jeremy-dev
              command: upgrade
              chartType: FilePath
              chartPath: $(Pipeline.Workspace)/xxx
              overrideValues: 'key1=val1'
              releaseName: dev
              force: true

- stage: PROD
  dependsOn: DEV
  displayName: "PROD"
  jobs:
  - deployment:
    environment: prod 
    strategy:                 
      runOnce:              
        deploy:    
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: chart
              downloadPath: '$(Pipeline.Workspace)'
          - task: KubectlInstaller@0
            displayName: 'Install Kubectl latest'
          - task: Kubernetes@1
            displayName: 'kubectl create namespace'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'AZURE_PROMEO'
              azureResourceGroup: '2023_Promeo_2'
              kubernetesCluster: 'lp2023_1'
              command: create
              arguments: 'ns noah-jeremy-dev'
            continueOnError: true
          - task: HelmDeploy@0
            displayName: 'helm upgrade'
            inputs:
              azureSubscription: 'AZURE_PROMEO'
              azureResourceGroup: '2023_Promeo_2'
              kubernetesCluster: 'lp2023_1'
              namespace: noah-jeremy-dev
              command: upgrade
              chartType: FilePath
              chartPath: $(Pipeline.Workspace)/xxx
              overrideValues: 'key1=val1'
              releaseName: prod
              force: true
