name: K8S_Helm_deployment

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Package
  displayName: "Package"

  jobs:
  - job: Package
    displayName: "Package"
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: chart'
      inputs:
        PathtoPublish: xxx
        ArtifactName: xxx

- stage: DEV
  dependsOn: Package
  displayName: "DEV"
  jobs:
  - deployment:
    environment: dev 
    strategy:                 
      runOnce:              
        deploy:    
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: xxx
              downloadPath: '$(Pipeline.Workspace)'
          - task: HelmDeploy@0
            displayName: 'helm upgrade'
            inputs:
              azureSubscription: 'AZURE_PROMEO'
              azureResourceGroup: 'itades'
              kubernetesCluster: itades-formation-001
              namespace: xxx
              command: upgrade
              chartType: FilePath
              chartPath: $(Pipeline.Workspace)/xxx
              overrideValues: 'env=dev'
              releaseName: xxx
              force: true
